version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: finance_container
    environment:
      POSTGRES_USER: finance_usr
      POSTGRES_PASSWORD: finance_psw
      POSTGRES_DB: financeDB
    volumes:
      - /data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"